source "https://rubygems.org"

ruby "2.1.0"

gem "sinatra"
gem "rake"
gem "thin"
gem "rack-contrib"
gem "websocket-rack"

group :development do
  gem "shotgun"
  gem "tux"
end

group :production do
  gem "pry"
end

